### ISSUE TITLE
Todos: Updated Elasticsearch and mapping type removal

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#134]
The [removal of mapping types and updating the ES version](https://github.com/PathwayCommons/grounding-search/issues/132) necessitates other updates:

## unstable (https://grounding.baderlab.org/)

- [x] Update the Elasticsearch version used [in Docker Compose, development branch](https://github.com/PathwayCommons/factoid-docker-config/issues/57)
- [x] Index and push ES data files to Zenodo (Sandbox) for caching
  - [x] Create a separate, development deposition so as to not interfere with the production version
  - see https://github.com/PathwayCommons/grounding-search#using-zenodo-to-store-index-dumps
- [x] Reboot grounding search container
- [x] Manually test grounding search at https://grounding.baderlab.org/

NB: This instance will be broken until these updates are made.

## beta (https://beta.biofactoid.org/)

- [x] Index and push ES data files to Zenodo for caching
- [x] [Update the grounding-search details in Docker Compose, beta branch](https://github.com/PathwayCommons/factoid-docker-config/issues/59) 
- [x] Push a beta version of the new grounding search to DockerHub
- [x] Pull and boot grounding search container

## production (https://biofactoid.org/)
- [x] [Update the grounding-search details in Docker Compose, main branch](https://github.com/PathwayCommons/factoid-docker-config/issues/59) 
- [x] [Bump the grounding-search version](https://github.com/PathwayCommons/grounding-search/issues/135)
- [x] Reboot grounding, index Docker Compose services
